name: Daily Mutual Fund Data Update

on:
  schedule:
    - cron: '30 13 * * *'  # Every day at 7 PM IST (13:30 UTC)
  workflow_dispatch:       # (optional: allows manual trigger)

jobs:
  update-mf-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install mftool
        run: pip install mftool

      - name: Run Python Script
        run: python daily_mf_fetcher.py

      - name: Commit and Push Updated JSON
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add public/mutual_funds.json
          git commit -m "🔁 Update mutual_funds.json automatically"
          git push
